# basic.yml
- name: Install and start nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Start nginx service
      service:
        name: nginx
        state: started
